# Generated by Django 4.2 on 2023-05-26 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loginapp', '0002_customsession_mobile_sms_qr_creation_randomsession'),
    ]

    operations = [
        migrations.CreateModel(
            name='LiveStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sessionID', models.CharField(max_length=2000)),
                ('username', models.CharField(max_length=2000)),
                ('product', models.CharField(max_length=100)),
                ('status', models.CharField(blank=True, max_length=50, null=True)),
                ('date_created', models.CharField(max_length=1000)),
                ('date_updated', models.CharField(blank=True, max_length=1000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='LiveUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_created=True)),
                ('session_id', models.CharField(max_length=2000)),
                ('username', models.CharField(max_length=2000)),
                ('product', models.CharField(max_length=255)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProductUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_created=True)),
                ('unique_id', models.CharField(max_length=2000)),
                ('username', models.CharField(max_length=2000)),
                ('product', models.CharField(max_length=255)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
