# Generated by Django 4.2 on 2023-08-14 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loginapp', '0006_linkbased_randomsession'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location_check',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=1000, unique=True)),
                ('usual', models.TextField()),
                ('unusual', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
