# Generated by Django 4.2 on 2023-08-21 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loginapp', '0007_location_check'),
    ]

    operations = [
        migrations.CreateModel(
            name='products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.CharField(max_length=1000, unique=True)),
                ('url', models.CharField(blank=True, max_length=1000)),
                ('ip', models.CharField(blank=True, max_length=1000)),
                ('status', models.CharField(default='active', max_length=100)),
            ],
        ),
    ]
