# Generated by Django 4.2 on 2024-01-18 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loginapp', '0011_alter_account_options_alter_account_managers_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='country',
            new_name='eventid',
        ),
        migrations.RenameField(
            model_name='account',
            old_name='event_id',
            new_name='safety_secruity_policy',
        ),
        migrations.RenameField(
            model_name='account',
            old_name='safty_secruity_policy',
            new_name='user_country',
        ),
        migrations.AlterField(
            model_name='account',
            name='newsletter_subscription',
            field=models.CharField(blank=True, default='Accepted', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='policy_status',
            field=models.CharField(blank=True, default='Accepted', max_length=255, null=True),
        ),
    ]
