# Generated by Django 4.2.10 on 2024-02-25 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("loginapp", "0012_rename_country_account_eventid_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="guestaccount",
            name="email",
            field=models.CharField(max_length=30),
        ),
    ]
