# Generated by Django 4.2.10 on 2024-02-25 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("loginapp", "0013_alter_guestaccount_email"),
    ]

    operations = [
        migrations.AddField(
            model_name="linkbased_randomsession",
            name="status",
            field=models.CharField(default="login", max_length=100),
            preserve_default=False,
        ),
    ]
