# Generated by Django 4.2.10 on 2024-02-25 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("loginapp", "0014_linkbased_randomsession_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="location_check",
            name="username",
            field=models.CharField(max_length=1000),
        ),
    ]
