# Generated by Django 4.2.10 on 2024-02-26 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("loginapp", "0015_alter_location_check_username"),
    ]

    operations = [
        migrations.AddField(
            model_name="account",
            name="current_task",
            field=models.CharField(default="", max_length=100),
        ),
    ]
